on:
  workflow_dispatch:

name: Release Hotfixes
permissions: write-all

jobs:
  check-release-job:

    runs-on: ubuntu-latest

    outputs:
      NeedRelease: ${{ steps.needRelease.outputs.NeedRelease == 'true' }}

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Git configuration and checkout develop
        run: |
          git config user.name MaksimillanoBot
          git config user.email shengelia.max@gmail.com
          git fetch
          git checkout -b develop origin/develop

      - name: Check if there are commit ahead of current master
        id: needRelease
        run: sh ./scripts/need-release.sh

  make-release-job:
    needs: check-release-job
    if: ${{ needs.check-release-job.outputs.NeedRelease == 'true' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Git configuration
        run: |
          git config user.name MaksimillanoBot
          git config user.email shengelia.max@gmail.com
          git fetch
          git checkout -b develop origin/develop

      - name: Create and checkout new release branch and update versions
        id: releaseBranchStep
        run: sh ./scripts/create-release.sh

      - name: Create Pull Request To MASTER
        run: gh pr create -B master -H ${{ steps.releaseBranchStep.outputs.ReleaseBranch }} --title 'New version updated' --body 'Created by Github action' --label 'automerge'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: Create Pull Request To DEVELOP
        run: gh pr create -B develop -H ${{ steps.releaseBranchStep.outputs.ReleaseBranch }} --title 'New version updated' --body 'Created by Github action' --label 'automerge'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
